booking_app/urls.py
from django.conf.urls import patterns, url
from booking_app import views
from booking_app.views import CustomerUpdate
from booking_app.views import VisitUpdate
from booking_app.views import TimeUpdate
from booking_app.views import CustomerDelete
from booking_app.views import VisitDelete
from booking_app.views import TimeDelete
from booking_app.views import TimeDetail
from booking_app.views import VisitDetail


from booking_app.views import CustomerDetail
from booking_app.views import BookingDetail





urlpatterns = patterns('booking_app.views',

    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^coach_index/$', views.coach_index, name='coach_index'),
    url(r'^add_customer/$', views.add_customer, name='add_customer'),
    url(r'^(?P<pk>\d+)/customer_update/$', CustomerUpdate.as_view(), name='customer_update'),
    url(r'^(?P<pk>\d+)/customer_delete/$', CustomerDelete.as_view(), name='customer_delete'),
    
    url(r'^(?P<customer_id>\d+)/$', views.visit, name='visit'),
    url(r'^(?P<customer_id>\d+)/new_visit/$', views.new_visit, name='new_visit'),
    url(r'^(?P<customer_id>\d+)/add_visit/$', views.add_visit, name='add_visit'),
    url(r'^(?P<pk>\d+)/visit_update/$', VisitUpdate.as_view(), name='visit_update'),
    url(r'^(?P<pk>\d+)/visit_delete/$', VisitDelete.as_view(), name='visit_delete'),
    
    url(r'^(?P<slug>[-\w]+)-(?P<visit_slug>[-\w]+)/$', views.detail, name='detail'),
    url(r'^(?P<visit_id>\d+)/new_time/$', views.new_time, name='new_time'),
    url(r'^(?P<visit_id>\d+)/add_time/$', views.add_time, name='add_time'),
    url(r'^(?P<pk>\d+)/time_update/$', TimeUpdate.as_view(), name='time_update'),
    url(r'^(?P<pk>\d+)/time_delete/$', TimeDelete.as_view(), name='time_delete'),

    url(r'^(?P<time_id>\d+)/(?P<booking_id>\d+)/bokningar/$', views.bokningar, name='bokningar'),
    url(r'^(?P<visit_id>\d+)/submit$', views.submit, name='submit'),
    url(r'^(?P<customer_id>\d+)/(?P<visit_id>\d+)/(?P<booking_id>\d+)/new_submit/$', views.new_submit, name='new_submit'),
    url(r'^(?P<customer_id>\d+)/(?P<visit_id>\d+)/(?P<booking_id>\d+)/$', views.update_booking, name='update_booking'),
    url(r'^(?P<customer_id>\d+)/(?P<visit_id>\d+)/(?P<time_id>\d+)/(?P<booking_id>\d+)/results/$', views.results, name='results'),

    url(r'^(?P<pk>\d+)/time_detail/$', TimeDetail.as_view(), name='time_detail'),
    url(r'^(?P<pk>\d+)/visit_detail/$', VisitDetail.as_view(), name='visit_detail'),


    url(r'^(?P<pk>\d+)/customer_detail/$', CustomerDetail.as_view(), name='customer_detail'),


    url(r'^bookinglist/$', views.BookingsView.as_view(), name='bookinglist'),
     
    url(r'^(?P<pk>\d+)/booking_detail/$', BookingDetail.as_view(), name='booking_detail'),  
    url(r'^(?P<customer_id>\d+)/(?P<visit_id>\d+)/(?P<time_id>\d+)/(?P<booking_id>\d+)/create_reminder/$', views.create_reminder, name='create_reminder'),
)

web_booking/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'web_booking4.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^booking_app/', include('booking_app.urls', namespace='booking_app')),
    #url(r'^booking_app/', include('booking_app.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

booking_app/models.py
#coding: utf8 
import os
from django.db import models
from django.forms import ModelForm
from django.core.urlresolvers import reverse
from django.template.defaultfilters import slugify
from autoslug import AutoSlugField

class Customer(models.Model):
	customer_name = models.CharField(max_length=50)
	created_date = models.DateTimeField(auto_now=True)
	slug = AutoSlugField(populate_from='customer_name')
	def __unicode__(self):
		return self.customer_name

class Visit(models.Model):
	customer = models.ForeignKey(Customer)
	visit_name = models.CharField(max_length=50)
	visit_date = models.DateField('Date')
	visit_slug = AutoSlugField(populate_from='visit_name', unique_with='customer__customer_name')
	def __unicode__(self):
		return self.visit_name


class Time(models.Model):
	visit = models.ForeignKey(Visit)
	datetime = models.DateTimeField('Date and time')
	capacity = models.IntegerField(default=1)
	location = models.CharField(max_length=50)
	def __unicode__(self):
		return "%s" % self.datetime
	class Meta:
		ordering = ['datetime']
	def is_capacity_filled(self):
		return self.booking_set.all().count() >= self.capacity

class Booking(models.Model):
	CLIENT_REMINDER_CHOICES = (
		('ten_m', '10 minuter'),
		('thirty_m', '30 minuter'),
        ('one_h', '1 timme'),
        ('two_h', '2 timmar'),
        ('one_d', '1 dag'),
        ('two_d', '2 dagar'),
        ('one_w', '1 vecka'),
        )
	time = models.ForeignKey(Time)
	client_firstname = models.CharField(max_length=50)
	client_lastname = models.CharField(max_length=50)
	client_mail = models.EmailField(max_length=100, blank=True)
	client_phone = models.CharField(max_length=50, blank=True)
	client_reminder = models.DateTimeField(null=True, choices=CLIENT_REMINDER_CHOICES)
	def __unicode__(self):
		return self.client_firstname

booking_app/forms.py
from django import forms
from datetimewidget.widgets import DateTimeWidget, DateWidget

from booking_app.models import Booking
from booking_app.models import Time
from booking_app.models import Visit
from booking_app.models import Customer


class BookingForm(forms.ModelForm):
	class Meta:
		model = Booking
		fields = [
			'client_firstname', 
			'client_lastname', 
			'client_phone', 
			'client_mail',
			
		]

class ReminderForm(forms.ModelForm):
	class Meta:
		model = Booking
		fields = [
			'client_reminder']

class VisitForm(forms.ModelForm):
	class Meta:
		model = Visit
		fields = ['visit_name', 'visit_date']
		dateTimeOptions = {
		'format': 'yyyy-mm-dd',
		'autoclose': True,
		'weekStart': 1,
		'pickerPosition': 'bottom-left',
		}
		widgets = {
			'visit_date': DateWidget(
				options = dateTimeOptions, 
				attrs={'id':"customer"}, 
				bootstrap_version=3
			)
		}

class CustomerForm(forms.ModelForm):
	class Meta:
		model = Customer
		fields = ['customer_name']

class TimeForm(forms.ModelForm):
    class Meta:
		model = Time
		fields = ['datetime', 'capacity', 'location',]
		dateTimeOptions = {
		'format': 'yyyy-mm-dd hh:ii',
		'autoclose': True,
		'weekStart': 1,
		}
		widgets = {
			'datetime': DateTimeWidget(
				options = dateTimeOptions, 
				attrs={'id':"visit"}, 
				bootstrap_version=3, 
			)
		}

booking_app/views.py
#coding: utf8 
import os
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.template import RequestContext, loader
from django.core.urlresolvers import reverse
from django.views import generic
from itertools import chain
from django.core.exceptions import ObjectDoesNotExist
from django.core.mail import EmailMultiAlternatives
from django.core.mail import send_mail
from django.conf import settings
from django.template.loader import render_to_string
import pytz
import datetime
from datetime import datetime, timedelta
from django.views.generic.edit import FormView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import DetailView
from django.core.urlresolvers import reverse_lazy
from django.utils.functional import lazy

from booking_app.mail_inv import sendAppointment
import datetime as dt
import icalendar
import uuid

from booking_app.models import Customer
from booking_app.models import Visit
from booking_app.models import Time
from booking_app.models import Booking
from booking_app.forms import BookingForm
from booking_app.forms import TimeForm
from booking_app.forms import VisitForm
from booking_app.forms import CustomerForm
from booking_app.forms import ReminderForm

#Customer
class IndexView(generic.ListView):
    template_name = 'booking_app/index.html'
    context_object_name = 'latest_customer_list'
    def get_queryset(self):
        return Customer.objects.order_by('-created_date')

def coach_index(request,):
    form = CustomerForm(request.POST or None)
    customer_list = Customer.objects.order_by('-created_date')
    return render(request, 'booking_app/coach_index.html', {
        'form': form, 
        'customer_list': customer_list
    })

def add_customer(request,):
    form = CustomerForm(request.POST or None)
    customer_list = Customer.objects.order_by('-created_date')
    if request.method == 'POST':
        if form.is_valid():
            customer_name = request.POST['customer_name']
            
            Customer.objects.create(customer_name = customer_name)
            return HttpResponseRedirect(reverse('booking_app:coach_index',))
        else:
            return render(request, 'booking_app/coach_index.html', {
                'form': form, 
                'customer_list': customer_list,
                'error_message': "Du måste skriva in ett företagsnamn",

            })

class CustomerUpdate(UpdateView):
    model = Customer
    def get_success_url(self):
        return reverse('booking_app:coach_index')

class CustomerDelete(DeleteView):
    model = Customer
    def get_success_url(self):
        return reverse('booking_app:coach_index')

#Visit
def visit(request, customer_id):
    customer = get_object_or_404(Customer, pk=customer_id)
    #customer = Customer.objects.get(slug=slug)
    
    return render(request, 'booking_app/visit.html', {
        'customer': customer,
    
    })

def new_visit(request, customer_id):
    customer = get_object_or_404(Customer, pk=customer_id)
    form = VisitForm(request.POST or None)
    return render(request, 'booking_app/new_visit.html', {
        'customer': customer, 
        'form': form
    })

def add_visit(request, customer_id):
    customer = get_object_or_404(Customer, pk=customer_id)
    form = VisitForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            visit_name = request.POST['visit_name']
            visit_date = request.POST['visit_date']
            Visit.objects.create(
                customer = customer,
                visit_name = visit_name, 
                visit_date = visit_date
            )
            return HttpResponseRedirect(reverse('booking_app:new_visit', 
                args=(customer.id,)
            ))
        else:
            return render(request, 'booking_app/new_visit.html', {
                'customer': customer, 
                'form': form,
                'error_message': "Du måste fylla i besöksnamn och datum"
            })

class VisitUpdate(UpdateView):
    model = Visit
    fields = ['visit_name', 'visit_date']
    def get_success_url(self):
        customer_id =  self.object.customer_id
        return reverse('booking_app:new_visit', args={customer_id})


class VisitDelete(DeleteView):
    model = Visit
    def get_success_url(self):
        customer_id =  self.object.customer_id
        return reverse('booking_app:new_visit', args={customer_id})

#Time
def detail(request, slug, visit_slug):
    customer = Customer.objects.get(slug=slug)
    visit = Visit.objects.get(visit_slug=visit_slug, customer__customer_name=customer)
    form = BookingForm(request.POST or None)
    return render(request, 'booking_app/detail.html', { 'form': form, 'visit': visit, 'customer': customer,})



def new_time(request, visit_id):
    visit = get_object_or_404(Visit, pk=visit_id)
    form = TimeForm(request.POST or None)
    customer_id = visit.customer_id
    return render(request, 'booking_app/new_time.html', {
        'visit': visit, 
        'form': form, 
        'customer_id': customer_id
    })

def add_time(request, visit_id):
    visit = get_object_or_404(Visit, pk=visit_id)
    form = TimeForm(request.POST or None)
    customer_id = visit.customer_id
    if request.method == 'POST':
        if form.is_valid():
            datetime = request.POST['datetime']
            capacity = request.POST['capacity']
            location = request.POST['location']

            Time.objects.create(
                visit = visit, 
                datetime = datetime, 
                capacity = capacity, 
                location = location, 
            )
            return render(request, 'booking_app/new_time.html', {
                'visit': visit,
                'form': form,
                'customer_id': customer_id
            })
        else:
            return render(request, 'booking_app/new_time.html', {
                'visit': visit, 
                'form': form, 
                'customer_id': customer_id,
                'error_message': "Du måste fylla i datum och tid, antal deltagare och plats"
    })

class TimeUpdate(UpdateView):
    model = Time
    fields = ['datetime', 'capacity', 'location',]
    def get_success_url(self):
        visit_id =  self.object.visit_id
        return reverse('booking_app:new_time', args={visit_id})

class TimeDelete(DeleteView):
    model = Time
    def get_success_url(self):
        visit_id =  self.object.visit_id
        return reverse('booking_app:new_time', args={visit_id})

#Booking
def bokningar(request, time_id, booking_id):
    time = get_object_or_404(Time, pk=time_id)
    booking = get_object_or_404(Booking, pk=booking_id)
    visit_id = time.visit_id
    return render(request, 'booking_app/bokningar.html', {
        'time': time, 
        'booking': booking, 
        'visit_id': visit_id
    })

def submit(request, visit_id):
    p = get_object_or_404(Visit, pk=visit_id)
    form = BookingForm(request.POST or None)
    try:
        selected_time = p.time_set.get(pk=request.POST['time'])
    except (KeyError, Time.DoesNotExist):
        
        return render(request, 'booking_app/detail.html', {
            'visit': p,
            'time_error_message': "Du har inte valt en tid.",             
            'form': form,
            })
    else:
        if request.method == 'POST':
            if form.is_valid():
                count_bookings = selected_time.booking_set.all().count()
                print count_bookings
                if count_bookings == selected_time.capacity:
                    return render(request, 'booking_app/detail.html', {
                    'visit': p,
                    'capacity_error_message': "Tyvärr har någon redan bokat den tiden",
                    'form': form,
                    })
                time_id = selected_time.id
                time = Time.objects.get(id=time_id)
                client_firstname = request.POST['client_firstname']
                client_lastname = request.POST['client_lastname']
                client_phone = request.POST['client_phone']
                client_mail = request.POST['client_mail']
                print p.customer_id
                create_booking = Booking.objects.create(
                    time = time, 
                    client_firstname = client_firstname, 
                    client_lastname = client_lastname, 
                    client_phone = client_phone, 
                    client_mail = client_mail,

                )
                booking = create_booking.id
                return HttpResponseRedirect(reverse('booking_app:results', 
                    args=(p.customer_id, p.id, time_id, booking,)
                ))
            else:
                return render(request, 'booking_app/detail.html', {
                'visit': p,
                'form_error_message': "Du måste ange för- och efternamn",
                
                'form': form,
                })
        

def new_submit(request, customer_id, visit_id, booking_id):
    p = get_object_or_404(Visit, pk=visit_id)
    customer = get_object_or_404(Customer, pk=customer_id)
    booking = get_object_or_404(Booking, pk=booking_id)
    form = BookingForm(request.POST or None)
    pub_from = request.GET.get('pub_date_from')
    if request.method == 'POST':
        if form.is_valid():
            
            
            #Hämtar id på nuvarnade bokning
            get_time_id = booking.time_id
            
            #selected_time blir den nya tiden man har valt eller den man hade innan om man inte väljer någon tid.
            selected_time = request.POST.get('time', get_time_id)

            #Hämtar tiden selected time
            new_time = Time.objects.get(pk=selected_time)

            #Om man har bytt tid
            if get_time_id != new_time.id:
                count_bookings = new_time.booking_set.all().count()

booking_app/templates/booking_app/base.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>{% block title %}Bokningsappen{% endblock %}</title>
	{% block head %}
	{% load staticfiles %}
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <link href="{% static 'booking_app/bootstrap/css/bootstrap.css' %}" rel="stylesheet" type="text/css"/>
    <script src="{% static 'booking_app/bootstrap/js/bootstrap.js' %}"></script>
    {{ form.media }}
	<link rel="stylesheet" type="text/css" href="{% static 'booking_app/style.css' %}" />
	{% endblock %}
</head>
<body>
{% block body %}{% endblock %}
</body>
</html>

booking_app/templates/booking_app/bookinglist.html
{% extends "booking_app/base.html" %}

{% block body %}
    {% for booking in bookinglist %}
    
    {{booking.time}} -- {{ booking.client_firstname }} {{ booking.client_lastname }} -- {{ booking.client_mail }} -- {{booking.client_phone }} -- {{booking.client_reminder}} -- {{booking.id}} <br />	
    
    {% endfor %}
{% endblock %}

booking_app/templates/booking_app/customer.html
{% extends "booking_app/base.html" %}

{% block body %}
<div id="rubrik">Företag </div><br />

<table width="100%" align="left">
	<tr>
        <th>Företag</th>
        <th>Skapad</th>
    </tr>
    <tr>
    	{% for customer in latest_customer_list %}

            <td>
                <a href="{% url 'booking_app:visit' customer.id %}">
                {{ customer.customer_name }}</a>
            </td>
            <td>
                {{customer.created_date|date:"d/n/Y"}}
            </td>

        </tr>
    {% endfor %}
</table>
    
{% endblock %}

booking_app/templates/booking_app/customer_confirm_delete.html
{% extends "booking_app/base.html" %}

{% block body %}

Är du säker på att du vill ta bort {{customer.customer_name}}?

<form action="" method="post">
    {% csrf_token %}
    <h5>
    <input type='submit' value='Ta bort' 
    button type="submit" class="btn btn-primary" />
    </h5>
</form>

<h5><a href="{% url 'booking_app:coach_index' %}">
<span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span>
 Tillbaka </a>
 </h5>

{% endblock %}

booking_app/templates/booking_app/customer_form.html
{% extends "booking_app/base.html" %}

{% block body %}

<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <h5><input type='submit' value='Spara ändringar' button type="submit" class="btn btn-primary" /></h5>
</form>

<h5><a href="{% url 'booking_app:coach_index' %}"><span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span> Tillbaka </a></h5>

{% endblock %}

booking_app/templates/booking_app/new_time.html
{% extends "booking_app/base.html" %}

    
{% block body %}



<div id="rubrik">{{visit.customer}} - {{visit.visit_name}} </div>



<h5><a href="{% url 'booking_app:visit_detail' visit.pk %}">Visa kontaktuppgifter för alla i det här besöket</a></h5>


<table width="100%" align="bottom" >
<tr><th>Måndag
    {% for time in visit.time_set.all %} 
        {% ifchanged %}
            {% if time.datetime|date:"l" == "Monday" %}
                
                     {{time.datetime|date:"j/n"}}
                    {% for time in visit.time_set.all|slice:"1" %}{% endfor %}        
                
            {% else %}
            {% endif %}
        {% endifchanged %}
    {% endfor %}
</th><th>Tisdag
    {% for time in visit.time_set.all %} 
        {% ifchanged %}
            {% if time.datetime|date:"l" == "Tuesday" %}
                
                     {{time.datetime|date:"j/n"}}
                    {% for time in visit.time_set.all|slice:"1" %}{% endfor %}        
                
            {% else %}
            {% endif %}
        {% endifchanged %}
    {% endfor %}
</th><th>Onsdag
    {% for time in visit.time_set.all %} 
        {% ifchanged %}
            {% if time.datetime|date:"l" == "Wednesday" %}
                
                     {{time.datetime|date:"j/n"}}
                    {% for time in visit.time_set.all|slice:"1" %}{% endfor %}        
                
            {% else %}
            {% endif %}
        {% endifchanged %}
    {% endfor %}
</th><th>Torsdag
    {% for time in visit.time_set.all %} 
        {% ifchanged %}
            {% if time.datetime|date:"l" == "Thursday" %}
                
                     {{time.datetime|date:"j/n"}}
                    {% for time in visit.time_set.all|slice:"1" %}{% endfor %}        
                
            {% else %}
            {% endif %}
        {% endifchanged %}
    {% endfor %}
</th><th>Fredag
    {% for time in visit.time_set.all %} 
        {% ifchanged %}
            {% if time.datetime|date:"l" == "Friday" %}
                
                     {{time.datetime|date:"j/n"}}
                    {% for time in visit.time_set.all|slice:"1" %}{% endfor %}        
                
            {% else %}
            {% endif %}
        {% endifchanged %}
    {% endfor %}</th>
</tr>
<tr>
<td>        
    {% for time in visit.time_set.all %}
        {% if time.datetime|date:"l" == "Monday" %}
            
                {% include "booking_app/tider_form.html" %}
            
        {% endif %}
    {% endfor %}
</td>
<td>        
    {% for time in visit.time_set.all %}
        {% if time.datetime|date:"l" == "Tuesday" %}
            
                {% include "booking_app/tider_form.html" %}
            
        {% endif %}
    {% endfor %}
</td>
<td>
    {% for time in visit.time_set.all %}
        {% if time.datetime|date:"l" == "Wednesday" %}
            
                {% include "booking_app/tider_form.html" %}
            
        {% endif %}
    {% endfor %}
</td>

<td>
    {% for time in visit.time_set.all %}
        {% if time.datetime|date:"l" == "Thursday" %}
            
                {% include "booking_app/tider_form.html" %}
            
        {% endif %}
    {% endfor %}

</td>
<td>
    {% for time in visit.time_set.all %}
        {% if time.datetime|date:"l" == "Friday" %}
            
                {% include "booking_app/tider_form.html" %}
            
        {% endif %}
    {% endfor %}
</td>
</tr>
</table>

<h5>Länk till det här besöket: <a href="http://127.0.0.1:8000/booking_app/{{visit.customer.slug}}-{{visit.visit_slug}}">http://127.0.0.1:8000/booking_app/{{visit.customer.slug}}-{{visit.visit_slug}}</a> </h5>
<form action="{% url 'booking_app:add_time' visit.id %}" method="post">
{% csrf_token %}


<table class="table1" width="100%" align="bottom">
<tr>
<th><label for="client_firstname">Datum och tid </label>{% csrf_token %}</th>
<th><label for="client_lastname">Antal deltagare </label>{% csrf_token %}</th>
<th><label for="client_phone">Plats </label>{% csrf_token %}</th>
</tr>
<tr>
<td>{{form.datetime}}</td>
<td>{{form.capacity}}</td>
<td>{{form.location}}</td>

</tr>
</table>

<h5><input type='submit' value='Lägg till' button type="submit" class="btn btn-primary" /></h5>
</form>

{% if error_message %}
<h4>Du måste fylla i <b>Datum och tid</b>, <b>Antal deltagare</b> och <b>Plats</b></h4>
{% endif %}

<h5><a href="{% url 'booking_app:new_visit' customer_id %}"><span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span> Tillbaka </a></h5>

{% endblock %}

booking_app/templates/booking_app/new_visit.html
{% extends "booking_app/base.html" %}

{% block body %}
<div id="rubrik">{{customer.customer_name}} </div>

<h4>Besökslista</h4>

<h5><b>
<a href="{% url 'booking_app:customer_detail' customer.pk %}">
Visa kontaktuppgifter för alla i det här företaget</a>
</b></h5>

<table width="100%" align="bottom">
    <tr>
    	<th>Besök</th>
    	<th>Datum</th>
    	<th>Ändra besök</th>
    	<th>Ta bort besök</th>
    </tr>
    {% for visit in customer.visit_set.all %}
    <tr>
    	<td>
            <a href="{% url 'booking_app:new_time' visit.id %}" >{{ visit.visit_name }}</a>
        </td>
    	<td>
            {{visit.visit_date|date:"Y-m-j"}}
        </td>
        <td>
            <a href="{% url 'booking_app:visit_update' visit.id %}" 
                STYLE="text-decoration: none">
            <span class="glyphicon glyphicon-edit" aria-hidden="true"></span></a>
        </td>
        <td>
        <a href="{% url 'booking_app:visit_delete' visit.id %}" 
            STYLE="text-decoration: none">
        <span class="glyphicon glyphicon-remove-circle" aria-hidden="true"></span></a>
        </td>
    {% endfor %}
    </tr>
</table>

<h4>Lägg till nytt besök</h4>

<form action="{% url 'booking_app:add_visit' customer.id %}" method="post">
{% csrf_token %}
<table width="100%" align="bottom">
    <tr>
        <th>
            <label for="visit_name">Besöksnamn</label>{% csrf_token %}
        </th>
        <th>
            <label for="visit_date">Datum för besök </label>{% csrf_token %}
        </th>
    </tr>
    <tr>
        <td>
            {{form.visit_name}}
        </td>
        <td>
            {{form.visit_date}}
        </td>
    </tr>
</table>
<h5><input type='submit' value='Lägg till' button type="submit" class="btn btn-primary" /></h5>
</form>

{% if error_message %}
<h4>Du måste fylla i <b>Besöksnamn</b> och <b>Datum för besök</b></h4>
{% endif %}

<h5><a href="{% url 'booking_app:coach_index' %}">
<span class="glyphicon glyphicon-arrow-left" aria-hidden="true">
    
</span> Tillbaka </a></h5>

{% endblock %}

booking_app/templates/booking_app/time_confirm_delete.html
{% extends "booking_app/base.html" %}

{% block body %}

Är du säker på att du vill ta bort {{time.datetime|time:"H:i"}} från den {{time.datetime|date:"j/n"}}?

<form action="" method="post">
    {% csrf_token %}
    <h5><input type='submit' value='Ta bort' button type="submit" class="btn btn-primary" /></h5>
</form>

<h5><a href="javascript:history.go(-1)"><span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span> Tillbaka </a></h5>

{% endblock %}

booking_app/templates/booking_app/time_detail.html
{% extends "booking_app/base.html" %}

{% block body %}


<div id="rubrik">{{time.datetime|date:"j/n"}} {{time.datetime|time:"H:i"}} </div>

{%for booking in time.booking_set.all %}
{{booking.client_firstname}} {{booking.client_lastname}} - {{booking.client_mail}} - {{booking.client_phone}}<br />
{% endfor %}


{% endblock %}

booking_app/templates/booking_app/time_form.html
{% extends "booking_app/base.html" %}

{% block body %}

<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <h5><input type='submit' value='Spara ändringar' button type="submit" class="btn btn-primary" /></h5>
</form>

<h5><a href="javascript:history.go(-1)"><span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span> Tillbaka </a></h5>

{% endblock %}

booking_app/templates/booking_app/visit_form.html
{% extends "booking_app/base.html" %}

{% block body %}

<form action="{% url 'booking_app:visit_update' visit.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <h5><input type='submit' value='Spara ändringar' button type="submit" class="btn btn-primary" /></h5>
</form>

<h5><a href="javascript:history.go(-1)"><span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span> Tillbaka </a></h5>

{% endblock %}